### ISSUE TITLE
ray_mask under the human

### ISSUE THREAD

**Issue by wangrui5781** [chungyiweng/humannerf#13]
我现在有一个自己拍照的数据想实验，使用ROMP获得了poses和betas，然后这个数据的相机内外参是基于标定的结果。但是基于您readme中的流程进行训练时候，每次生成的 ray_mask， 都会出现在照片中人物靠下的地方，至少在腰部以下，请问您知道是什么原因导致的这个问题吗，是不是要对内外参做一些变换什么的，图片是4096*3072的分辨率

**Comment by wangrui5781** [comment]
而且我发现每张图的 ray_mask 都好像是90度旋转后的情况，就是站立的人的ray_mask会是一个躺平的类似矩形的形状

**Comment by sycamore27** [comment]
我和你遇到了相似的问题！！！也是用ROMP估计SMPL参数，跑自己拍的视频。但patch sample过程中inter_mask = np.bitwise_and(sel_ray_mask, ray_mask)结果常常全为False导致程序断掉，有点不知道为什么

**Comment by chungyiweng** [comment]
I'm going to close the issue since no further responses are received.

**Comment by sycamore27** [comment]
> 我现在有一个自己拍照的数据想实验，使用ROMP获得了poses和betas，然后这个数据的相机内外参是基于标定的结果。但是基于您readme中的流程进行训练时候，每次生成的 ray_mask， 都会出现在照片中人物靠下的地方，至少在腰部以下，请问您知道是什么原因导致的这个问题吗，是不是要对内外参做一些变换什么的，图片是4096*3072的分辨率

Hello, have you solved this problem?
 I also found that if the intrinsics and extrinsics estimated by PROM can correctly generate the bounding box, but theintrinsics and extrinsics  calibrated by the camera originally will be wrong, which is really inexplicable. If you have solved it, could you answer me? Thank you very much.
