### ISSUE TITLE
some quetions about approx_gaussian_bone_volumes

### ISSUE THREAD

**Issue by ssy-sheshe** [chungyiweng/humannerf#14]
if the joint is a parent node，the way to generate the bone volume is by generating  a Gaussian distribution centered on the midpoint of the parent and child nodes。I don't understand the way ,because it means that the weight of the point closer to the joint is  smaller,which is unreasonable.Can you please elaborate it for me?
thanks
https://github.com/chungyiweng/humannerf/blob/7389c4049c0d5b14afdbac41a605ddad9d51dd4a/core/utils/body_util.py#L274

**Comment by chungyiweng** [comment]
For a skeleton, a joint has an impact on the bone that attaches it. If a point is close to a joint, it might be affected by the two bones attaching to the joint, while if it is in the middle of a bone, it is less affected by the neighbor bones. We use a 3D Gaussian function centered on the midpoint of a bone to roughly leverage the intuition.
