### ISSUE TITLE
Evaluation produces empty images.

### ISSUE THREAD

**Issue by HelloRicky123** [chungyiweng/humannerf#15]
Thanks for your contribution of the code and paper!

I followed the readme and downloaded the trained model, but the evaluation gave empty images. The `mv_output['x_skel']` in network.py looks like following:
<img src="https://user-images.githubusercontent.com/25146499/178227986-8707cd38-41ff-42eb-adb0-21ba954af44f.png" width="200" />

Could you please give me some advice to debug this problem?

Thanks!

**Comment by chungyiweng** [comment]
It's weird that you get empty images. You might want to check whether the ray_mask is not all-zeros and you did shoot rays toward the image. You can also dump the rendered images as numeric arrays to see if anything does not work as expected. Try to train the model by yourself to see if it can learn something meaningful.

In addition, you might want to double-confirm that you did follow the instruction very carefully and make sure you did everything thoroughly and correctly.

**Comment by HelloRicky123** [comment]
The point cloud in the question is a part of the following, which is chunked in the code.
<img src="https://user-images.githubusercontent.com/25146499/178437677-132efcbd-c0dc-46c3-897c-72c95b7d87a6.png" width="200" />

I can project the sample points on the image and see reasonable results. However, the non-rigid deformation mlp_offset.py seems strange. The input XYZ to mlp_offset.py is about 0.8, but the output deformation is 0.2, it is too large for a 'small correction'. Now I am retraining the network without the non-rigid deformation to see whether it works.

The projected points on the image:
<img src="https://user-images.githubusercontent.com/25146499/178439877-25c6c6cb-a28d-49ce-a358-b10a2ba3635b.png" width="200" />

**Comment by HelloRicky123** [comment]
The training failed at last. But I have found the original reason for empty evaluation images. I found the downloaded basicModel_neutral_lbs_10_207_0_v1.0.0.pkl is 38M. And after removing chumpy it is 104M. It seems that previously I forget to replace the basicModel_neutral_lbs_10_207_0_v1.0.0.pkl in `humannerf/third_parties/smpl/models`.

By the way, the result is extremely good.

**Comment by Dipankar1997161** [comment]
> Thanks for your contribution of the code and paper!
> 
> I followed the readme and downloaded the trained model, but the evaluation gave empty images. The `mv_output['x_skel']` in network.py looks like following: <img alt="" width="200" src="https://user-images.githubusercontent.com/25146499/178227986-8707cd38-41ff-42eb-adb0-21ba954af44f.png">
> 
> Could you please give me some advice to debug this problem?
> 
> Thanks!

hello @HelloRicky123, I was wondering how did you got the image for the mv_output['x_skel'] and how did you project the rays on the image,

I am actually using a custom data and it would be helpful for me to debug the empty images. 
I hope you can respond.

**Comment by LeeBeen1** [comment]
@HelloRicky123 Hi~, could you please tell me how to remove chumpy, when I run chean_ch.py, the pkl was still the same size
