### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by Andyen512** [chungyiweng/humannerf#17]
Hello,
How long about the training time for training the subject 387 in ZJU-Mocap dataset. I'm now training the subject 387 for 15hours with 7000 Iters, is there too slow?

**Comment by HelloRicky123** [comment]
I am also using this excellent repo. On my machine training 20 iters costs 10 seconds. So 7000 iters should costs about 1 hour.

**Comment by Andyen512** [comment]
I'm using 4 TITAN XP to train.  Do you know the reson that I'm too slow? Do you modify some configs?

**Comment by Andyen512** [comment]
![image](https://user-images.githubusercontent.com/74585868/178707276-d6bbc686-dd6c-4a24-91a2-5416775d723a.png)
![image](https://user-images.githubusercontent.com/74585868/178707290-c3a788ab-90b3-468e-8a89-533373cfb35a.png)
My GPU-Util  is 0 except cuda4, so I guess whether I should modify somewhere to use the other gpu?

**Comment by HelloRicky123** [comment]
Sorry I am not sure about it. I did not change the config file. I use 4 V100 GPU to train the model.

**Comment by Andyen512** [comment]
oh thx, I think maybe the machine difference contribute the training speed difference.

**Comment by chungyiweng** [comment]
@HelloRicky123, Thanks for providing your experience and suggestions!

@Andyen512, the training is significantly slower than expected. I guess the bottleneck might be I/O. You might want to check if others share the server and use a lot of bandwidth. If possible, switch to more high-end GPUs or a clean server to see if the situation improves.
