### ISSUE TITLE
animate model

### ISSUE THREAD

**Issue by Andyen512** [chungyiweng/humannerf#19]
Can the trained HumanNerf model be used to generate some new unseen poses?

**Comment by chungyiweng** [comment]
Yes, it has the capability of being applied to unseen poses but we did not evaluate it carefully as it's not our focus.

**Comment by mgholamikn** [comment]
Thank you for sharing the code. Could you please let me know how I can give random 3D poses (smpl param) as input to the model?

**Comment by Erickrus** [comment]
can I assume, T-pose is not in the dataset, and it can be rendered. So, does that mean, unseen pose can be rendered ?

**Comment by Erickrus** [comment]
I tested if you modify core/data/human_nerf/tpose.py (dst_poses), give it a different value, e.g. np.ones(72) * 0.1, it could render some unseen pose. 

https://user-images.githubusercontent.com/1734553/187589441-e437b31f-b0f4-4315-99ab-d500b8a3cb2a.mp4

And I have a question, here, how is dst_poses represented ? 
    24x3 relative angles? 
    range from (-1,1) ?

Many thanks

**Comment by Erickrus** [comment]
Render **unseen pose**

If you want to change T-pose to an **unseen pose** (let's say Y-pose), you can reference [SMPL FAQ P23](https://files.is.tue.mpg.de/black/talks/SMPL-made-simple-FAQs.pdf). Find out the corresponding joint ids for both shoulders. And then in `core/data/human_nerf/tpose.py` line 140. Add 2 new lines:

```python
dst_poses[16*3+2] =  1.0 # Left shoulder  rotate +1/pi*180 = +57 deg
dst_poses[17*3+2] = -1.0 # right shoulder rotate -1/pi*180 = -57 deg
```

Have fun!

https://user-images.githubusercontent.com/1734553/187606515-08c02199-78c5-4068-b8e8-5565c8c4ae56.mp4
