### ISSUE TITLE
Load from check point

### ISSUE THREAD

**Issue by afiretony** [chungyiweng/humannerf#20]
Hi, thanks for sharing your great work!
Do you have any script for continuing train from saved checkpoint, it seems in `train.py` there isn't args for passing the checkpoint path etc., thanks!

**Comment by HelloRicky123** [comment]
Thanks to the excellent code.

Resume code is in  `humannerf/core/train/trainers/human_nerf/trainer.py`.  
You can run it with 
```
python train.py --cfg configs/human_nerf/zju_mocap/392/adventure.yaml resume True
```

**Comment by afiretony** [comment]
thanks!

**Comment by afiretony** [comment]
> Thanks to the excellent code.
> 
> Resume code is in `humannerf/core/train/trainers/human_nerf/trainer.py`. You can run it with
> 
> ```
> python train.py --cfg configs/human_nerf/zju_mocap/392/adventure.yaml resume True
> ```
