### ISSUE TITLE
stack expects each tensor to be equal size, but got [2，....

### ISSUE THREAD

**Issue by MtYCNN** [chungyiweng/humannerf#21]
Thanks for the source code provided by the author, but there is such a problem. Whether using single card or multi card training, you can train normally when using batchsize=1. However, when the batchsize is not 1, an error of "stack expectations each tense to be equal size, but got [2, 2400, 3] at entry 0 and [2, 2332, 3] at entry 1" will occur.
How to solve it? I'm sorry to trouble you.

**Comment by chungyiweng** [comment]
Currently, we only support batchsize=1. Please keep it unchanged. Sorry for the inconvenience.
