### ISSUE TITLE
training time+

### ISSUE THREAD

**Issue by Andyen512** [chungyiweng/humannerf#23]
#17 
I think the  significantly slower may because of the image size and the num of frames.
My training data is 1920*1080 and I use 538 frames to train. The decreasing num of the frame can decrease the training time. But when I change the 'resize_img_scale' from 0.5 to 0.2, the training time for 20Iter doesn't decrease. Do you know the reason?  I think the num of ray depend on the image size, so the small image will spend less time for training right?

**Comment by chungyiweng** [comment]
The training time per iteration should NOT be affected by the image size and the frame numbers, as it only depends on the number of rays, which is determined by the patch size and numbers.
