### ISSUE TITLE
Start/end frame index about youtube data.

### ISSUE THREAD

**Issue by wyysf-98** [chungyiweng/humannerf#24]
Thanks for your great work!
You mentioned that the human subject in the clip should shows most of body regions. However, in the  _invisible_ data, the back region is unseen during the video in project page.
Could you please provide more details about the _youtube_ data, such as the start/end frame index and the sampling interval etc. ;)

**Comment by chungyiweng** [comment]
Hello,

For invisible, I used the clip roughly between 00:01:16~00:01:23 without skipping any frames.

However, if possible, I hope you do not use these YouTube videos as a benchmark dataset. The dancing artist grants me to access his videos only for this work. They are not intended to be a public dataset for the community. Please respect his copyright and privacy.

If you want to make an algorithm comparison, please consider using ZJU-MoCap, other public datasets, or self-captured data. Thank you for taking care of this issue seriously.

**Comment by wyysf-98** [comment]
Thanks for your reply and reminder! I just want to run a local test, and I will respect this copyright and privacy.
