### ISSUE TITLE
Question about Refined T-Pose

### ISSUE THREAD

**Issue by Xiaoming-Zhao** [chungyiweng/humannerf#25]
Hi @chungyiweng , congrats on this great work and thanks a lot for open-sourcing the code. I have a question about the data preprocessing for data in the wild and hope you can give me a hand. Specifically, there is a line to offset `tpose_joints` with `pelvis_pos`:
https://github.com/chungyiweng/humannerf/blob/7389c4049c0d5b14afdbac41a605ddad9d51dd4a/tools/prepare_wild/prepare_dataset.py#L72-L73

After this step, the `tpose_joints` for `mesh_infos` of each frame will differ from `canonical_joints`. However, I do not find some code snippets to compensate such difference later. Probably I miss something. May I know whether you mind helping me understand why this is needed? Thanks a lot in advance.

**Comment by chungyiweng** [comment]
Hello Xiaoming,

I did this just for ease of implementation -- you can refer to [the issue](https://github.com/chungyiweng/humannerf/issues/18#issuecomment-1188079285) to get more details. 

The offset is compensated by storing pelvis_pos as a global translation (i.e., Th) that will be applied after global rotation (i.e., Rh).
