### ISSUE TITLE
dimensions of patch_imgs in unpack_imgs() function

### ISSUE THREAD

**Issue by rohana96** [chungyiweng/humannerf#27]
Thanks for releasing the code.

I was wondering if the intended dimensions of patch_imgs in `unpack_imgs() ` function is `(N_patch, patch_size, patch_size, 3)` or `(N_patch, frame_height,  frame_width, 3)`. The Dataset class creates `target_patches` of dimensions `(N_patch, patch_size, patch_size, 3)` which get passed to `unpack_imgs()` as `targets`.

**trainer.py:** 

```
def _unpack_imgs(rgbs, patch_masks, bgcolor, targets, div_indices):
    N_patch = len(div_indices) - 1
    assert patch_masks.shape[0] == N_patch
    assert targets.shape[0] == N_patch

    patch_imgs = bgcolor.expand(targets.shape).clone() # (N_patch, H, W, 3)
    for i in range(N_patch):
        patch_imgs[i, patch_masks[i]] = rgbs[div_indices[i]:div_indices[i+1]]

    return patch_imgs
```

**train.py (Dataset class)** :
```
        targets = []
        for i in range(cfg.patch.N_patches):
            x_min, y_min = patch_info['xy_min'][i] 
            x_max, y_max = patch_info['xy_max'][i]
            targets.append(img[y_min:y_max, x_min:x_max])
        target_patches = np.stack(targets, axis=0) # (N_patches, P, P, 3)
```

Thanks in advance! :)

**Comment by chungyiweng** [comment]
Hello, 

The dimension of patch_imgs in `unpack_imgs` is `(N_patch, patch_size, patch_size, 3)`. I just realized my comment is a bit confusing. The `(H, W)` in the comment was meant to be patch height and width actually. Thanks for your questions!
