### ISSUE TITLE
Novel Poses

### ISSUE THREAD

**Issue by mgholamikn** [chungyiweng/humannerf#28]
Thank you for sharing the code. Could you please let me know how I could give random 3D poses (smpl param) as input to the model?

**Comment by Andyen512** [comment]
you can use [VIBE](https://github.com/mkocabas/VIBE) or [ROMP](https://github.com/Arthur151/ROMP) to extract a sequence of SMPL pose and then render your trained model by using run.py.

**Comment by chungyiweng** [comment]
@Andyen512 
Thanks for your help with responding to the issue.

@mgholamikn 
It's a little bit tricky to run novel poses on the current code base. These are several suggestions:

1)  As Andy said, you can use an off-the-shelf 3D pose detector or MoCap data to get a sequence of SMPL parameters.

2) You need to transform SMPL parameters to the network input (e.g., dst_Rs, dst_Ts, cnl_gtfms. etc.). Please refer to core/data/humane_nerf/train.py for the details. 

3) Optionally, you might want to ignore pose correction and/or non-rigid motion prediction in the rendering process as they should be used for the observed sequence only (i.e., training frames).

I hope this is helpful for your implementation of novel pose renderings.
