### ISSUE TITLE
camera parameters

### ISSUE THREAD

**Issue by scao7** [chungyiweng/humannerf#30]
I am trying to apply the method to my own video data. I used the VIBE model to extract the weak perspective camera parameters however I don't know how to convert the VIBE camera parameter into intrinsic and extrinsic camera parameter. Could you please provide a script to do that? 

Thanks

**Comment by afiretony** [comment]
Hi, you can find it in Issue #1 https://github.com/chungyiweng/humannerf/issues/1#issuecomment-1153743401

**Comment by scao7** [comment]
Thanks,
It solves my question
