### ISSUE TITLE
the drive pose is different with the render pose

### ISSUE THREAD

**Issue by Andyen512** [chungyiweng/humannerf#31]
![000085_](https://user-images.githubusercontent.com/74585868/183064899-4647f8d8-92ec-4e1d-bc81-96adf3c54717.png)
![QQ截图20220805190641](https://user-images.githubusercontent.com/74585868/183065183-fbf53a96-0558-4e66-ae41-18248813a21d.jpg)

Hi chungyi,
I use the top picture's SMPL pose to drive the bottom picture. But I can't see the feet of the person in the bottom picture. What's wrong with it, does it related to the cam_intrinsics and cam_extrinsics?

**Comment by Erickrus** [comment]
How is this solved ?
