### ISSUE TITLE
Question about camera poses

### ISSUE THREAD

**Issue by Jia-Wei-Liu** [chungyiweng/humannerf#32]
Hi! Thank you for releasing this wonderful work! 

As recommended, I am using VIBE to get human pose and camera pose. Could you please explain what does the camera extrinsic predicted from VIBE mean? It seems the R=I, and there is only translation in VIBE's camera poses. I understand that Rh and Th from human poses are the global rotation and translation of the SMPL model, and it rotates the camera to output the final camera extrinsic matrix. I wonder how is this camera extrinsic matrix different from those calibrated using COLMAP? Is there any relation between the camera poses predicted from your model and those calibrated by COLMAP?

I also want to check is your camera poses based on OpenCV camera coordinates or OpenGL camera coordinates?

Thank you very much!

**Comment by LTS1989** [comment]
I am using SPIN to get the metadata and I am also confused by the camera settings. Could you please explain how you calculate the intrinsics and extrinsics from SPIN's output? Thank you so much.

**Comment by chungyiweng** [comment]
@Jia-Wei-Liu 

There is no direct relation between the camera poses predicted by VIBE (or other 3D human pose estimators) and thoses by COLMAP.  VIBE is solving for a camera such that the predicted 3D human body, after projection, can match the 2D observations, while COLMAP optimizes for cameras to align extracted 3D point clouds with 2D feature points. 

If you want to combine the VIBE and COLMAP camera matrices, you have to make sure the posed 3D human model (from VIBE) and point clouds (from COLMAP), when being projected to the camera plane (i.e. the 2D image), look correct. I know there is a follow-up work, [NeuMan](https://arxiv.org/abs/2203.12575), trying to solve the problem (see the section "Scene-SMPL Alignment"). You might want to refer to the paper to get the details.

We used OpenCV camera coordinates btw.


@LTS1989 

Converting SPIN output to appropriate camera matrices is similar to what we did for VIBE. You may refer to the [issue ](https://github.com/chungyiweng/humannerf/issues/1) to know how it works. Alternatively, you can just use VIBE instead -- SPIN and VIBE has similar performance.
