### ISSUE TITLE
about pose prior

### ISSUE THREAD

**Issue by yf1019** [chungyiweng/humannerf#33]
hi yiweng,

Thanks to your great work. 

I noticed that you involved a pre-defined skinning prior, called 'motion_weights_priors' in the code. Actually I think this is a very accurate prior for the initial smpl mesh. May I know how do you calculate these parameters of this skinning prior? 

Thanks a lot.

**Comment by chungyiweng** [comment]
Hello,

The 'motion_weights_priors' consists of ellipsoidal 3D Gaussian around each body bone. It roughly approximates body bone regions in a pre-defined canonical pose (T-pose, in our case). For more details, you may refer to the [supplementary material](https://openaccess.thecvf.com/content/CVPR2022/supplemental/Weng_HumanNeRF_Free-Viewpoint_Rendering_CVPR_2022_supplemental.pdf) (Section D - Optimizing delta W_c).

**Comment by yf1019** [comment]
Hi yiweng,

Thanks for your quick reply! I know that 'motion_weights_priors' are ellipsoidal 3D Gaussians around body bones. But my question is how to get these 3D gaussian ellipsoids. This is not mentioned in the Supp?

**Comment by yf1019** [comment]
Specificly, how to get the Bone/heads/joints stds?

**Comment by chungyiweng** [comment]
Hi Yang,

The stds were just determined arbitrarily based on my intuitions (e.g., the torso is thicker than arms, the head size is bigger than feet, etc.). They are not fine-tuned and the result should not be very sensitive to these values.

**Comment by yf1019** [comment]
Got it. I think I made some mistake in my experiment. Thanks again for your very quick reply~
