### ISSUE TITLE
custom wild mocular dataset training problem

### ISSUE THREAD

**Issue by solomon-ma** [chungyiweng/humannerf#4]
Problem:
I followed your wild mocular dataset generation steps to do.
But for training, I got the below error log.
I appreciated if you can tell me how to modify the problem.

**error log:**
Loading model from: /home/huima_phd/workspace/human/humannerf/third_parties/lpips/weights/v0.1/vgg.pth
Load Progress Dataset ...
[Dataset Path] wild/monocular
 -- Total Frames: 16
************************************
[Dataset Path] wild/monocular
 -- Total Frames: 233
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    main()
  File "train.py", line 26, in main
    train_dataloader=train_loader)
  File "core/train/trainers/human_nerf/trainer.py", line 131, in train
    for batch_idx, batch in enumerate(train_dataloader):
  File "/home/huima_phd/anaconda3/envs/humannerf/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/huima_phd/anaconda3/envs/humannerf/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/huima_phd/anaconda3/envs/humannerf/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/huima_phd/anaconda3/envs/humannerf/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/huima_phd/anaconda3/envs/humannerf/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/huima_phd/anaconda3/envs/humannerf/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/huima_phd/anaconda3/envs/humannerf/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "core/data/human_nerf/train.py", line 358, in __getitem__
    far=far)
  File "core/data/human_nerf/train.py", line 278, in sample_patch_rays
    H=H, W=W)
  File "core/data/human_nerf/train.py", line 160, in get_patch_ray_indices
    patch_size, H, W)
  File "core/data/human_nerf/train.py", line 198, in _get_patch_ray_indices
    size=[1], replace=False)[0]
  File "mtrand.pyx", line 903, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken

**custom wild monocular metadata.json:**
"000000": {"betas": [-0.16328100860118866, 0.11383125185966492, 0.6279183626174927, 3.3971972465515137, 0.19168108701705933, 0.32847487926483154, -0.544987678527832, 0.39935165643692017, 0.5813453197479248, -0.04764612019062042], "cam_extrinsics": [[1.0, 0.0, 0.0, 0.00833630096167326], [0.0, 1.0, 0.0, 0.2196706384420395], [0.0, 0.0, 1.0, 39.878773057000494], [0.0, 0.0, 0.0, 1.0]], "cam_intrinsics": [[17428.94454960086, 0.0, 326.0287322998047], [0.0, 17428.94454960086, 732.1641540527344], [0.0, 0.0, 1.0]], "poses": [3.080174684524536, -0.0966465175151825, 0.036192912608385086, -0.10561415553092957, -0.015074647031724453, 0.07820028811693192, -0.14865875244140625, -0.0269086305052042, -0.08692160993814468, 0.20863130688667297, 0.009184405207633972, -0.0124925896525383, 0.418530136346817, -0.15048101544380188, -0.09652546048164368, 0.7397283315658569, 0.011715290136635303, 0.050302810966968536, 0.007428893819451332, 0.0005256514414213598, 0.012498755939304829, -0.26333701610565186, 0.1799420416355133, -0.01325867511332035, -0.23553016781806946, -0.11562228947877884, 0.021505778655409813, 0.0016091171419247985, -0.015369821339845657, -0.01547306403517723, -0.11434655636548996, 0.049089375883340836, 0.015336933545768261, -0.11120732873678207, 0.07338123768568039, 0.03814869746565819, -0.12273751944303513, 0.08997315913438797, 0.08220325410366058, 0.01601310446858406, 0.1044275164604187, -0.459648072719574, -0.0534483976662159, 0.021979140117764473, 0.4401393234729767, 0.10073123127222061, -0.09283072501420975, -0.05564229562878609, 0.04708145931363106, 0.017706334590911865, -0.8051507472991943, 0.21630819141864777, 0.08788160979747772, 0.7991366386413574, 0.19693699479103088, -0.3376815915107727, 0.020134467631578445, 0.1598469465970993, 0.3192528188228607, -0.095707967877388, 0.21532699465751648, -0.0403285026550293, -0.03279117867350578, 0.06930424273014069, 0.04943617060780525, -0.04457174241542816, -0.07478336244821548, 0.03657335415482521, -0.4092167019844055, -0.03395747020840645, -0.03833270072937012, 0.3159177899360657]},    
"000001": {"betas": [-0.1617068648338318, 0.12678277492523193, 0.5753797888755798, 3.099853515625, 0.14373239874839783, 0.22298412024974823, -0.5110366344451904, 0.4210997521877289, 0.6230412721633911, -0.005347482860088348], "cam_extrinsics": [[1.0, 0.0, 0.0, 0.0037134503945708275], [0.0, 1.0, 0.0, 0.20970091223716736], [0.0, 0.0, 1.0, 39.289053144665736], [0.0, 0.0, 0.0, 1.0]], "cam_intrinsics": [[17559.203981384017, 0.0, 323.33060704047233], [0.0, 17559.203981384017, 732.0699862130775], [0.0, 0.0, 1.0]], "poses": [3.052389144897461, -0.09576679766178131, 0.058825381100177765, -0.07060839980840683, -0.003000709693878889, 0.08578658103942871, -0.09765227138996124, -0.040437210351228714, -0.09089448302984238, 0.20354194939136505, 0.012548615224659443, -0.01579756662249565, 0.3758326470851898, -0.15159450471401215, -0.09618940949440002, 0.6298882961273193, 0.01751238852739334, 0.04437557980418205, 0.016005076467990875, -0.0006281638634391129, 0.008040579035878181, -0.2563464641571045, 0.18947477638721466, -0.02024911344051361, -0.22879332304000854, -0.12115583568811417, 0.024520987644791603, 0.005036815535277128, -0.014141506515443325, -0.013349002227187157, -0.11878697574138641, 0.04788254573941231, 0.01596507616341114, -0.111212357878685, 0.07218535244464874, 0.0370543897151947, -0.09944402426481247, 0.09720675647258759, 0.08127012848854065, 0.01970353163778782, 0.1121639534831047, -0.45524880290031433, -0.04709416627883911, 0.010194375179708004, 0.4349527657032013, 0.12492376565933228, -0.08530746400356293, -0.04616457596421242, 0.04945855215191841, 0.01800312101840973, -0.7869526743888855, 0.22305075824260712, 0.08780833333730698, 0.7871159315109253, 0.20992636680603027, -0.33902212977409363, 0.0048898025415837765, 0.19550392031669617, 0.3357231318950653, -0.08214118331670761, 0.2365020364522934, -0.042223017662763596, -0.019867008551955223, 0.08082664757966995, 0.05293732136487961, -0.05421726033091545, -0.08319265395402908, 0.03800441697239876, -0.4022020995616913, -0.04312872886657715, -0.04276105388998985, 0.31069087982177734]},    
"000002": {"betas": [-0.15868523716926575, 0.04492112994194031, 0.5778285264968872, 3.1710026264190674, 0.1750844120979309, 0.21373547613620758, -0.5038304328918457, 0.42985105514526367, 0.6381741762161255, -0.007328055799007416], "cam_extrinsics": [[1.0, 0.0, 0.0, 0.00679317070171237], [0.0, 1.0, 0.0, 0.21068531274795532], [0.0, 0.0, 1.0, 38.70970904827123], [0.0, 0.0, 0.0, 1.0]], "cam_intrinsics": [[17547.98587125286, 0.0, 322.93404955503786], [0.0, 17547.98587125286, 732.2837608207469], [0.0, 0.0, 1.0]], "poses": [3.0620646476745605, -0.08606187999248505, 0.04501306638121605, -0.05604463815689087, 0.0042025139555335045, 0.0941864475607872, -0.08926979452371597, -0.04587658494710922, -0.08972795307636261, 0.2057066112756729, 0.01087829377502203, -0.0169803686439991, 0.33017948269844055, -0.16104312241077423, -0.09374722093343735, 0.6008079051971436, 0.02052280493080616, 0.04279279708862305, 0.01252574659883976, -0.002380402060225606, 0.009856760501861572, -0.253021776676178, 0.1920269876718521, -0.01979898102581501, -0.2281314581632614, -0.11981823295354843, 0.02738257497549057, 0.009408002719283104, -0.016451172530651093, -0.01279402431100607, -0.12322132289409637, 0.050567254424095154, 0.016536276787519455, -0.11260774731636047, 0.07796500623226166, 0.034246064722537994, -0.10670053958892822, 0.10095509886741638, 0.08650747686624527, 0.018761172890663147, 0.11674315482378006, -0.45247554779052734, -0.04906364157795906, 0.005188377108424902, 0.43167784810066223, 0.1296195089817047, -0.08162445574998856, -0.04775657504796982, 0.04511559009552002, 0.009957032278180122, -0.7972688674926758, 0.2237519472837448, 0.09592072665691376, 0.7992170453071594, 0.21006172895431519, -0.3334171175956726, 0.0006652290467172861, 0.1944415271282196, 0.32971253991127014, -0.07785870879888535, 0.2385045439004898, -0.03428387641906738, -0.01634952612221241, 0.08242541551589966, 0.045961227267980576, -0.05723969638347626, -0.08438142389059067, 0.034524448215961456, -0.3986980617046356, -0.04237676039338112, -0.03871304541826248, 0.3055134117603302]},       
...
"000232": {"betas": [0.05657580494880676, 0.08467844128608704, 0.450006902217865, 2.293916940689087, 0.12574145197868347, 0.09546003490686417, -0.32668378949165344, 0.32228362560272217, 0.5719388723373413, 0.013897163793444633], "cam_extrinsics": [[1.0, 0.0, 0.0, 0.007118375971913338], [0.0, 1.0, 0.0, 0.1774924248456955], [0.0, 0.0, 1.0, 39.59851877741778], [0.0, 0.0, 0.0, 1.0]], "cam_intrinsics": [[18191.557779011495, 0.0, 369.4830732802437], [0.0, 18191.557779011495, 782.5204946353333], [0.0, 0.0, 1.0]], "poses": [-3.0971875190734863, 0.09100408107042313, 0.04630040004849434, -0.09203365445137024, 0.021483099088072777, 0.09766323864459991, -0.12352200597524643, -0.028421081602573395, -0.051476143300533295, 0.22441944479942322, 0.00839716661721468, -0.01751641556620598, 0.23835481703281403, -0.17126396298408508, -0.08508238941431046, 0.44775140285491943, 0.0389258898794651, 0.023526528850197792, -0.04403155297040939, -0.0031590056605637074, -0.0006984308711253107, -0.22450357675552368, 0.25555816292762756, -0.06192311272025108, -0.22256743907928467, -0.16413035988807678, 0.0561036579310894, 0.026690157130360603, -0.01770428568124771, -0.010632225312292576, -0.07626678794622421, 0.009529994800686836, 0.018050260841846466, -0.1262538880109787, 0.09429602324962616, -0.008411473594605923, -0.14442481100559235, 0.062088169157505035, 0.05382183939218521, 0.018625836819410324, 0.19007529318332672, -0.22667230665683746, -0.08481372147798538, -0.11665184795856476, 0.19354987144470215, -0.014612068422138691, -0.05220254510641098, -0.008670642971992493, -0.02788003906607628, 0.14612923562526703, -0.46956685185432434, 0.15867525339126587, -0.08979817479848862, 0.49875396490097046, 0.15303124487400055, -0.48291441798210144, 0.08898085355758667, 0.2045193314552307, 0.6336097717285156, -0.2059175670146942, 0.23074741661548615, -0.0729251503944397, 0.027056191116571426, 0.03464338928461075, 0.08952753245830536, -0.08961787074804306, -0.05111432448029518, 0.0792808011174202, -0.42849838733673096, 0.0020163131412118673, -0.07899215817451477, 0.34120574593544006]}

**mask_image:**
![000001](https://user-images.githubusercontent.com/16464813/174343749-6af0d6b2-892b-4994-b9a1-d6a9c4bf9abf.png)

**Comment by hongsiyu** [comment]
Have you solved this problem?

**Comment by chungyiweng** [comment]
Hello,

It's a little bit hard to know what's going on there. My best guess is some of the camera coefficients might be incorrect. Could you kindly check all of the video frames have the correct camera coefficients? 

For debugging, you might want to use only one video frame, say "000000", in your training data to see if the problem still exists. If so you can further check if the camera pose looks good to you. I hope this helps.

**Comment by chungyiweng** [comment]
Hello, 

I'm going to close the issue as I did not see further responses. Feel free to re-open the issue if the problem still exists.

**Comment by sunwenzhang1996** [comment]
Have you solved this problem?

**Comment by AABLOOOM** [comment]
Hi, have you solved the problem? And how to check if the camera poses are correct? I checked the masks and camera intrinsics&extrinsics, they all look good to me.

**Comment by Dipankar1997161** [comment]
> Hi, have you solved the problem? And how to check if the camera poses are correct? I checked the masks and camera intrinsics&extrinsics, they all look good to me.

hey, where you able to solve this problem? 

Please let me know
