### ISSUE TITLE
Always “Produce empty images; reload the init model.”

### ISSUE THREAD

**Issue by surheaven** [chungyiweng/humannerf#43]
![1663748709084](https://user-images.githubusercontent.com/89247297/191455066-6cd831cc-8a76-4df6-9e36-f7baac2e2fdf.png)
When I was training my own data, I found that I could only train 100iter per epoch, and each epoch prompted”Produce empty images; reload the init model.“

**Comment by chuanyues** [comment]
Hi, I had the same issue "Produce empty images; reload the init model". This consistently happens on all zju-mocap datasets and only happens with adventure.yaml. The config with single_gpu.yaml had no problem. 

Can you share how you resolve the issue?

**Comment by chuanyues** [comment]
@surheaven Hi, I had the same issue "Produce empty images; reload the init model". This consistently happens on all zju-mocap datasets and only happens with adventure.yaml. The config with single_gpu.yaml had no problem.

Can you share how you resolve the issue?
