### ISSUE TITLE
Question about table 1 in the paper.

### ISSUE THREAD

**Issue by HelloRicky123** [chungyiweng/humannerf#6]
Thanks for your contribution of the code and paper.
I have questions about table 1 in the paper. It seems that Neural Body in table 1 has higher accuracy than in its original paper. I guess it is because Neural Body is trained on 4 views and the 3 training views are also in the test views. Is it?
Thanks.

**Comment by chungyiweng** [comment]
1) Yes, it is probably the root cause but I'm not quite sure.
2) FID is used for the synthesis when the ground truth is not available. In our case, we do have the ground truth image of novel views in ZJU-MoCap data. So we adapt PSNR, SSIM, and LPIPS as our metrics.
