### ISSUE TITLE
Eq.16 in supplementary material

### ISSUE THREAD

**Issue by xyIsHere** [chungyiweng/humannerf#69]
Dear author,

Thank you for your great work. I'm new to the human nerf area. Could you explain why the equation is defined like this to compute the observation-to-canonical transformation? Is there any reference I can read to understand this equation?

**Comment by theAdityaRamesh** [comment]
Hi, i'm not an author. You can refer this paper [Vid2Actor](https://arxiv.org/abs/2012.12884) (Eq 10,11).

**Comment by xyIsHere** [comment]
Thanks a lot! I also checked that paper before but still didn't fully get understand it. Do u know what does the inverse do in this equation?
![image](https://github.com/chungyiweng/humannerf/assets/26050719/6852b301-dd79-4a24-8d28-2844aa80c6ed)
