### ISSUE TITLE
How to find the canonical_joints.pkl

### ISSUE THREAD

**Issue by xjchao7** [chungyiweng/humannerf#7]
Thank you for your perfect work.  When I try to inference the zju_mocap 387 model, it will met "FileNotFoundError: [Errno 2] No such file or directory: 'dataset/zju_mocap/387/canonical_joints.pkl'". Could you please ask me how to get the canonical_joints.pkl ?

Thank you very much.

**Comment by zhan-xu** [comment]
did you run prepare_dataset.py? canonical_joints.pkl comes from that step

**Comment by chungyiweng** [comment]
Thanks, @zhan-xu, for your response. 

Yes, please do run prepare_dataset.py to get canonical_joints.pkl. The details can be found on the [github page](https://github.com/chungyiweng/humannerf#prepare-a-dataset).

**Comment by xjchao7** [comment]
> 

Got it. Thank you for both of your responses.
