### ISSUE TITLE
Update -  Dataloader issue with custom training 

### ISSUE THREAD

**Issue by Dipankar1997161** [chungyiweng/humannerf#70]
Hello @chungyiweng,

I saw the following issue regarding the data loader here https://github.com/chungyiweng/humannerf/issues/4#issue-1275272277. I have the same issue right now. From the error log there, its may not be clear,  so here is a little more info.

I compared the zju mocap and monocular data using "patch_mode" and got the following error log
Zju-mocap
![zjumocap img](https://github.com/chungyiweng/humannerf/assets/85514219/18a3cf53-da28-4646-a3bd-0387acfbc3ca)

Monocular - in my case Human3.6m
![wild patches](https://github.com/chungyiweng/humannerf/assets/85514219/8860b98b-e846-4616-8e22-b9ef8e7f823e)

The 'rays', 'far', 'patch_indices' are empty in monocular cases which means apparently there might be error in the SMPL joint locations in the near and far plane which falls along the camera rays for sampling.

Any suggestions on what could be the possible reason for this and any solution advice on how this can be achieved?
Looking forward to discuss on this. 

My image and mask are as follows
![001611](https://github.com/chungyiweng/humannerf/assets/85514219/ab431312-ea40-4744-82b9-2e821c07d9bc)
![001611](https://github.com/chungyiweng/humannerf/assets/85514219/c50fecbf-5b1e-45a9-b5aa-311d799e4682)

**Comment by Dipankar1997161** [comment]
The issue is probably with the "Joints" value in the mesh_info.pkl, becoz of which 2 things happen:
1. Ray, Far list return empty list
2. Bbox value range is enormous in all the 3 axis

hence when the rays are projected, the candidate_mask returns 0, thus terminating the data_loader.

I may be wrong too, Would like to hear from you on this @chungyiweng

**Comment by DredLiu03** [comment]
Hi, have you solved the problem?
