### ISSUE TITLE
How to evaluate the results?

### ISSUE THREAD

**Issue by cxyhust** [chungyiweng/humannerf#8]
How to evaluate the results?

**Comment by chungyiweng** [comment]
I used the following evaluation protocol to create table 1.

1) For unseen cameras, I temporally sample the video frames at the rate of 30. For example, for subject 387, I evaluated the model at frames 0, 30, 60, .., and 510 for all unseen 22 cameras.

2) I evaluate the model on the whole image with a black background.

3) Normalize the image values to 0-1. Use the code below to compute PSNR

```
def psnr_metric(img_pred, img_gt):
    mse = np.mean((img_pred - img_gt)**2)
    psnr = -10 * np.log(mse) / np.log(10)
    return psnr
```

4) Normalize the image values to 0-1. Compute SSIM via the [structural_similarity](https://scikit-image.org/docs/dev/api/skimage.metrics.html#skimage.metrics.structural_similarity) function provided by scikit-image package.

5) Normalize the image values to -1~1. Compute LPIPS where VGG is used as the backbone model. 

I hope this makes it clear to evaluate the trained model.

**Comment by zshyang** [comment]
If possible, would you mind releasing the evaluation code? I will understand if it is not possible.

**Comment by yuchenrao** [comment]
Does anyone duplicate the evaluation code? It would be thankful if anyone could share here (duplicate / original version). Thanks!

**Comment by Jia-Wei-Liu** [comment]
Thanks for the detail explanation. 
If possible, could you please share the evaluation code for comparison? Thank you very much!
It would also be thankful if anyone could share the reproduced evaluation code. Thank you!

**Comment by yuchenrao** [comment]
Actually I wrote an evaluation script by myself, and got reasonable results compared with the paper. Feel free to check it and let me know if anything is wrong. The only problem is that you need to add `skip=30` to pick every 30th frame, and change `view` in the yaml file. 
```
import skimage
import os

import torch
import numpy as np
from tqdm import tqdm
from PIL import Image

from core.data import create_dataloader
from core.nets import create_network
from core.utils.train_util import cpu_data_to_gpu
from core.utils.image_util import ImageWriter, to_8b_image, to_8b3ch_image

from configs import cfg, args

from third_parties.lpips import LPIPS

EXCLUDE_KEYS_TO_GPU = ['frame_name',
                       'img_width', 'img_height']

def load_network():
    model = create_network()
    ckpt_path = os.path.join(cfg.logdir, f'{cfg.load_net}.tar')
    ckpt = torch.load(ckpt_path, map_location='cuda:0')
    model.load_state_dict(ckpt['network'], strict=False)
    print('load network from ', ckpt_path)
    return model.cuda().deploy_mlps_to_secondary_gpus()


def unpack_alpha_map(alpha_vals, ray_mask, width, height):
    alpha_map = np.zeros((height * width), dtype='float32')
    alpha_map[ray_mask] = alpha_vals
    return alpha_map.reshape((height, width))


def unpack_to_image(width, height, ray_mask, bgcolor,
                    rgb, alpha, truth=None):
    
    rgb_image = np.full((height * width, 3), bgcolor, dtype='float32')
    truth_image = np.full((height * width, 3), bgcolor, dtype='float32')

    rgb_image[ray_mask] = rgb
    rgb_image = to_8b_image(rgb_image.reshape((height, width, 3)))

    if truth is not None:
        truth_image[ray_mask] = truth
        truth_image = to_8b_image(truth_image.reshape((height, width, 3)))

    alpha_map = unpack_alpha_map(alpha, ray_mask, width, height)
    alpha_image  = to_8b3ch_image(alpha_map)

    return rgb_image, alpha_image, truth_image

def psnr_metric(img_pred, img_gt):
    mse = np.mean((img_pred - img_gt)**2)
    psnr = -10 * np.log(mse) / np.log(10)
    return psnr

def scale_for_lpips(image_tensor):
    return image_tensor * 2. - 1.


def get_loss(rgb, target):
    lpips = LPIPS(net='vgg')#.cuda()
    lpips_loss = lpips(scale_for_lpips(rgb.permute(0, 3, 1, 2)), 
                       scale_for_lpips(target.permute(0, 3, 1, 2)))
    return torch.mean(lpips_loss).cpu().detach().numpy()

def evaluate():
    cfg.perturb = 0.

    psnr_l = []
    ssim_l = []
    lpips_l = []

    model = load_network()
    test_loader = create_dataloader('movement')

    model.eval()
    for idx, batch in enumerate(tqdm(test_loader)):
        for k, v in batch.items():
            batch[k] = v[0]

        data = cpu_data_to_gpu(
                    batch,
                    exclude_keys=EXCLUDE_KEYS_TO_GPU + ['target_rgbs'])

        with torch.no_grad():
            net_output = model(**data, iter_val=cfg.eval_iter)

        rgb = net_output['rgb']
        alpha = net_output['alpha']

        width = batch['img_width']
        height = batch['img_height']
        ray_mask = batch['ray_mask']

        pred_img, alpha_img, gt_img = \
            unpack_to_image(
                width, height, ray_mask, np.array(cfg.bgcolor)/255.,
                rgb.data.cpu().numpy(),
                alpha.data.cpu().numpy(),
                batch['target_rgbs'])

        pred_img_norm = pred_img / pred_img.max()
        gt_img_norm = gt_img / gt_img.max()

        # get evaluation
        psnr_l.append(psnr_metric(pred_img_norm, gt_img_norm))
        ssim_l.append(skimage.metrics.structural_similarity(pred_img_norm, gt_img_norm, multichannel=True))
        lpips_loss = get_loss(rgb=torch.from_numpy(pred_img_norm).float().unsqueeze(0), target=torch.from_numpy(gt_img_norm).float().unsqueeze(0))
        lpips_l.append(lpips_loss)
        

    return psnr_l, ssim_l, lpips_l

psnr_l, ssim_l, lpips_l = evaluate()
print (np.array(psnr_l).mean())
print (np.array(ssim_l).mean())
print (np.array(lpips_l).mean())
```

**Comment by Yzmblog** [comment]
> Actually I wrote an evaluation script by myself, and got reasonable results compared with the paper. Feel free to check it and let me know if anything is wrong. The only problem is that you need to add `skip=30` to pick every 30th frame, and change `view` in the yaml file.
> 
> ```
> import skimage
> import os
> 
> import torch
> import numpy as np
> from tqdm import tqdm
> from PIL import Image
> 
> from core.data import create_dataloader
> from core.nets import create_network
> from core.utils.train_util import cpu_data_to_gpu
> from core.utils.image_util import ImageWriter, to_8b_image, to_8b3ch_image
> 
> from configs import cfg, args
> 
> from third_parties.lpips import LPIPS
> 
> EXCLUDE_KEYS_TO_GPU = ['frame_name',
>                        'img_width', 'img_height']
> 
> def load_network():
>     model = create_network()
>     ckpt_path = os.path.join(cfg.logdir, f'{cfg.load_net}.tar')
>     ckpt = torch.load(ckpt_path, map_location='cuda:0')
>     model.load_state_dict(ckpt['network'], strict=False)
>     print('load network from ', ckpt_path)
>     return model.cuda().deploy_mlps_to_secondary_gpus()
> 
> 
> def unpack_alpha_map(alpha_vals, ray_mask, width, height):
>     alpha_map = np.zeros((height * width), dtype='float32')
>     alpha_map[ray_mask] = alpha_vals
>     return alpha_map.reshape((height, width))
> 
> 
> def unpack_to_image(width, height, ray_mask, bgcolor,
>                     rgb, alpha, truth=None):
>     
>     rgb_image = np.full((height * width, 3), bgcolor, dtype='float32')
>     truth_image = np.full((height * width, 3), bgcolor, dtype='float32')
> 
>     rgb_image[ray_mask] = rgb
>     rgb_image = to_8b_image(rgb_image.reshape((height, width, 3)))
> 
>     if truth is not None:
>         truth_image[ray_mask] = truth
>         truth_image = to_8b_image(truth_image.reshape((height, width, 3)))
> 
>     alpha_map = unpack_alpha_map(alpha, ray_mask, width, height)
>     alpha_image  = to_8b3ch_image(alpha_map)
> 
>     return rgb_image, alpha_image, truth_image
> 
> def psnr_metric(img_pred, img_gt):
>     mse = np.mean((img_pred - img_gt)**2)
>     psnr = -10 * np.log(mse) / np.log(10)
>     return psnr
> 
> def scale_for_lpips(image_tensor):
>     return image_tensor * 2. - 1.
> 
> 
> def get_loss(rgb, target):
>     lpips = LPIPS(net='vgg')#.cuda()
>     lpips_loss = lpips(scale_for_lpips(rgb.permute(0, 3, 1, 2)), 
>                        scale_for_lpips(target.permute(0, 3, 1, 2)))
>     return torch.mean(lpips_loss).cpu().detach().numpy()
> 
> def evaluate():
>     cfg.perturb = 0.
> 
>     psnr_l = []
>     ssim_l = []
>     lpips_l = []
> 
>     model = load_network()
>     test_loader = create_dataloader('movement')
> 
>     model.eval()
>     for idx, batch in enumerate(tqdm(test_loader)):
>         for k, v in batch.items():
>             batch[k] = v[0]
> 
>         data = cpu_data_to_gpu(
>                     batch,
>                     exclude_keys=EXCLUDE_KEYS_TO_GPU + ['target_rgbs'])
> 
>         with torch.no_grad():
>             net_output = model(**data, iter_val=cfg.eval_iter)
> 
>         rgb = net_output['rgb']
>         alpha = net_output['alpha']
> 
>         width = batch['img_width']
>         height = batch['img_height']
>         ray_mask = batch['ray_mask']
> 
>         pred_img, alpha_img, gt_img = \
>             unpack_to_image(
>                 width, height, ray_mask, np.array(cfg.bgcolor)/255.,
>                 rgb.data.cpu().numpy(),
>                 alpha.data.cpu().numpy(),
>                 batch['target_rgbs'])
> 
>         pred_img_norm = pred_img / pred_img.max()
>         gt_img_norm = gt_img / gt_img.max()
> 
>         # get evaluation
>         psnr_l.append(psnr_metric(pred_img_norm, gt_img_norm))
>         ssim_l.append(skimage.metrics.structural_similarity(pred_img_norm, gt_img_norm, multichannel=True))
>         lpips_loss = get_loss(rgb=torch.from_numpy(pred_img_norm).float().unsqueeze(0), target=torch.from_numpy(gt_img_norm).float().unsqueeze(0))
>         lpips_l.append(lpips_loss)
>         
> 
>     return psnr_l, ssim_l, lpips_l
> 
> psnr_l, ssim_l, lpips_l = evaluate()
> print (np.array(psnr_l).mean())
> print (np.array(ssim_l).mean())
> print (np.array(lpips_l).mean())
> ```

Hi, Did you get the same result in the paper report using the pretrained model? I got some small difference in my evaluation code, still didn't figure out the reasons.

**Comment by yuchenrao** [comment]
> > Actually I wrote an evaluation script by myself, and got reasonable results compared with the paper. Feel free to check it and let me know if anything is wrong. The only problem is that you need to add `skip=30` to pick every 30th frame, and change `view` in the yaml file.
> > ```
> > import skimage
> > import os
> > 
> > import torch
> > import numpy as np
> > from tqdm import tqdm
> > from PIL import Image
> > 
> > from core.data import create_dataloader
> > from core.nets import create_network
> > from core.utils.train_util import cpu_data_to_gpu
> > from core.utils.image_util import ImageWriter, to_8b_image, to_8b3ch_image
> > 
> > from configs import cfg, args
> > 
> > from third_parties.lpips import LPIPS
> > 
> > EXCLUDE_KEYS_TO_GPU = ['frame_name',
> >                        'img_width', 'img_height']
> > 
> > def load_network():
> >     model = create_network()
> >     ckpt_path = os.path.join(cfg.logdir, f'{cfg.load_net}.tar')
> >     ckpt = torch.load(ckpt_path, map_location='cuda:0')
> >     model.load_state_dict(ckpt['network'], strict=False)
> >     print('load network from ', ckpt_path)
> >     return model.cuda().deploy_mlps_to_secondary_gpus()
> > 
> > 
> > def unpack_alpha_map(alpha_vals, ray_mask, width, height):
> >     alpha_map = np.zeros((height * width), dtype='float32')
> >     alpha_map[ray_mask] = alpha_vals
> >     return alpha_map.reshape((height, width))
> > 
> > 
> > def unpack_to_image(width, height, ray_mask, bgcolor,
> >                     rgb, alpha, truth=None):
> >     
> >     rgb_image = np.full((height * width, 3), bgcolor, dtype='float32')
> >     truth_image = np.full((height * width, 3), bgcolor, dtype='float32')
> > 
> >     rgb_image[ray_mask] = rgb
> >     rgb_image = to_8b_image(rgb_image.reshape((height, width, 3)))
> > 
> >     if truth is not None:
> >         truth_image[ray_mask] = truth
> >         truth_image = to_8b_image(truth_image.reshape((height, width, 3)))
> > 
> >     alpha_map = unpack_alpha_map(alpha, ray_mask, width, height)
> >     alpha_image  = to_8b3ch_image(alpha_map)
> > 
> >     return rgb_image, alpha_image, truth_image
> > 
> > def psnr_metric(img_pred, img_gt):
> >     mse = np.mean((img_pred - img_gt)**2)
> >     psnr = -10 * np.log(mse) / np.log(10)
> >     return psnr
> > 
> > def scale_for_lpips(image_tensor):
> >     return image_tensor * 2. - 1.
> > 
> > 
> > def get_loss(rgb, target):
> >     lpips = LPIPS(net='vgg')#.cuda()
> >     lpips_loss = lpips(scale_for_lpips(rgb.permute(0, 3, 1, 2)), 
> >                        scale_for_lpips(target.permute(0, 3, 1, 2)))
> >     return torch.mean(lpips_loss).cpu().detach().numpy()
> > 
> > def evaluate():
> >     cfg.perturb = 0.
> > 
> >     psnr_l = []
> >     ssim_l = []
> >     lpips_l = []
> > 
> >     model = load_network()
> >     test_loader = create_dataloader('movement')
> > 
> >     model.eval()
> >     for idx, batch in enumerate(tqdm(test_loader)):
> >         for k, v in batch.items():
> >             batch[k] = v[0]
> > 
> >         data = cpu_data_to_gpu(
> >                     batch,
> >                     exclude_keys=EXCLUDE_KEYS_TO_GPU + ['target_rgbs'])
> > 
> >         with torch.no_grad():
> >             net_output = model(**data, iter_val=cfg.eval_iter)
> > 
> >         rgb = net_output['rgb']
> >         alpha = net_output['alpha']
> > 
> >         width = batch['img_width']
> >         height = batch['img_height']
> >         ray_mask = batch['ray_mask']
> > 
> >         pred_img, alpha_img, gt_img = \
> >             unpack_to_image(
> >                 width, height, ray_mask, np.array(cfg.bgcolor)/255.,
> >                 rgb.data.cpu().numpy(),
> >                 alpha.data.cpu().numpy(),
> >                 batch['target_rgbs'])
> > 
> >         pred_img_norm = pred_img / pred_img.max()
> >         gt_img_norm = gt_img / gt_img.max()
> > 
> >         # get evaluation
> >         psnr_l.append(psnr_metric(pred_img_norm, gt_img_norm))
> >         ssim_l.append(skimage.metrics.structural_similarity(pred_img_norm, gt_img_norm, multichannel=True))
> >         lpips_loss = get_loss(rgb=torch.from_numpy(pred_img_norm).float().unsqueeze(0), target=torch.from_numpy(gt_img_norm).float().unsqueeze(0))
> >         lpips_l.append(lpips_loss)
> >         
> > 
> >     return psnr_l, ssim_l, lpips_l
> > 
> > psnr_l, ssim_l, lpips_l = evaluate()
> > print (np.array(psnr_l).mean())
> > print (np.array(ssim_l).mean())
> > print (np.array(lpips_l).mean())
> > ```
> 
> Hi, Did you get the same result in the paper report using the pretrained model? I got some small difference in my evaluation code, still didn't figure out the reasons.

I have a small difference, which seems acceptable. Here are my evaluation results on the downloaded model: 28.04, 0.9628, 35.65 for 387.

**Comment by Yzmblog** [comment]
> 28.04, 0.9628, 35.65 for 387.

Thanks for your quick reply, my psnr evaluation results on the downloaded model is 27.61 for 387, maybe there are some difference in my code, thanks!

**Comment by SDNAFIO** [comment]
Using the script provided above and evaluating on the pre-trained datasets, I get reasonable results from the PSNR and SSIM. However, my LPIPS results seem to be far off, they are about ~9.0. 

Does anyone have an idea what the problem could be?

**Comment by SDNAFIO** [comment]
@chungyiweng 
Are the results published in the paper computed from the provided models?

And why is the evaluation code still not published?
Being able to compare the results quantitatively using the exact same protocol is a necessity for any subsequent work.

**Comment by liwenssss** [comment]
@yuchenrao Hi, I run your evaluate code but the running time is so long :
![image](https://user-images.githubusercontent.com/11902259/194984224-b00c8849-5bdf-495d-881b-d66611515c72.png)
is it normal?

**Comment by escapefreeg** [comment]
I also wrote an evaluation code and obtained the exact same evaluation indicators in the paper. 
Code address: https://github.com/escapefreeg/humannerf-eval
![terminal_output](https://user-images.githubusercontent.com/42019181/195025148-35348003-e8ef-46d5-8bbd-eeeeb037935c.png)
![paper_output](https://user-images.githubusercontent.com/42019181/195025196-0c4aaf05-de1b-4efa-8a80-68d7fedefb79.png)
If there are errors or improvements in the code, please feel free to contact me!

**Comment by liwenssss** [comment]
> I also wrote an evaluation code and obtained the exact same evaluation indicators in the paper. Code address: https://github.com/escapefreeg/humannerf-eval ![terminal_output](https://user-images.githubusercontent.com/42019181/195025148-35348003-e8ef-46d5-8bbd-eeeeb037935c.png) ![paper_output](https://user-images.githubusercontent.com/42019181/195025196-0c4aaf05-de1b-4efa-8a80-68d7fedefb79.png) If there are errors or improvements in the code, please feel free to contact me!

@escapefreeg Thanks for your code. There is still some difference in my result. I run the code on a single RTX 3080, but it is useful for my next step experiment. 
![image](https://user-images.githubusercontent.com/11902259/195053971-3ce14af2-6dd5-4728-acd4-35d8268f2411.png)

**Comment by escapefreeg** [comment]
> > I also wrote an evaluation code and obtained the exact same evaluation indicators in the paper. Code address: https://github.com/escapefreeg/humannerf-eval ![terminal_output](https://user-images.githubusercontent.com/42019181/195025148-35348003-e8ef-46d5-8bbd-eeeeb037935c.png) ![paper_output](https://user-images.githubusercontent.com/42019181/195025196-0c4aaf05-de1b-4efa-8a80-68d7fedefb79.png) If there are errors or improvements in the code, please feel free to contact me!
> 
> @escapefreeg Thanks for your code. There is still some difference in my result. I run the code on a single RTX 3080, but it is useful for my next step experiment. ![image](https://user-images.githubusercontent.com/11902259/195053971-3ce14af2-6dd5-4728-acd4-35d8268f2411.png)

You‘re welcome, glad that I could help.

**Comment by Yang-Kaixing** [comment]
> > > I also wrote an evaluation code and obtained the exact same evaluation indicators in the paper. Code address: https://github.com/escapefreeg/humannerf-eval ![terminal_output](https://user-images.githubusercontent.com/42019181/195025148-35348003-e8ef-46d5-8bbd-eeeeb037935c.png) ![paper_output](https://user-images.githubusercontent.com/42019181/195025196-0c4aaf05-de1b-4efa-8a80-68d7fedefb79.png) If there are errors or improvements in the code, please feel free to contact me!
> > 
> > 
> > @escapefreeg Thanks for your code. There is still some difference in my result. I run the code on a single RTX 3080, but it is useful for my next step experiment. ![image](https://user-images.githubusercontent.com/11902259/195053971-3ce14af2-6dd5-4728-acd4-35d8268f2411.png)
> 
> You‘re welcome, glad that I could help.

@chungyiweng 
I retrained the model with the original Human-NeRF code and then ran the validation with this code and the results I got here were beter than the one in paper. I would like to ask if the experimental results in the paper are the ones with floating.
![image](https://user-images.githubusercontent.com/50354191/202161919-a5f0607d-fb68-4915-a2c9-34664a61553d.png)

**Comment by Andyen512** [comment]
> > > I also wrote an evaluation code and obtained the exact same evaluation indicators in the paper. Code address: https://github.com/escapefreeg/humannerf-eval ![terminal_output](https://user-images.githubusercontent.com/42019181/195025148-35348003-e8ef-46d5-8bbd-eeeeb037935c.png) ![paper_output](https://user-images.githubusercontent.com/42019181/195025196-0c4aaf05-de1b-4efa-8a80-68d7fedefb79.png) If there are errors or improvements in the code, please feel free to contact me!
> > 
> > 
> > @escapefreeg Thanks for your code. There is still some difference in my result. I run the code on a single RTX 3080, but it is useful for my next step experiment. ![image](https://user-images.githubusercontent.com/11902259/195053971-3ce14af2-6dd5-4728-acd4-35d8268f2411.png)
> 
> You‘re welcome, glad that I could help.

Does the results in table1 tested on the training data(training view)?

**Comment by escapefreeg** [comment]
> 

No, I'm evaluating on test data (camera index is 1-22, and image is taken every 30 frames)

**Comment by escapefreeg** [comment]
> > > > I also wrote an evaluation code and obtained the exact same evaluation indicators in the paper. Code address: https://github.com/escapefreeg/humannerf-eval ![terminal_output](https://user-images.githubusercontent.com/42019181/195025148-35348003-e8ef-46d5-8bbd-eeeeb037935c.png) ![paper_output](https://user-images.githubusercontent.com/42019181/195025196-0c4aaf05-de1b-4efa-8a80-68d7fedefb79.png) If there are errors or improvements in the code, please feel free to contact me!
> > > 
> > > 
> > > @escapefreeg Thanks for your code. There is still some difference in my result. I run the code on a single RTX 3080, but it is useful for my next step experiment. ![image](https://user-images.githubusercontent.com/11902259/195053971-3ce14af2-6dd5-4728-acd4-35d8268f2411.png)
> > 
> > 
> > You‘re welcome, glad that I could help.
> 
> Does the results in table1 tested on the training data(training view)?

No, The results are evaluated on test data (camera index is 1-22, and image is taken every 30 frames)

**Comment by Andyen512** [comment]
> > > > > > I also wrote an evaluation code and obtained the exact same evaluation indicators in the paper. Code address: https://github.com/escapefreeg/humannerf-eval ![terminal_output](https://user-images.githubusercontent.com/42019181/195025148-35348003-e8ef-46d5-8bbd-eeeeb037935c.png) ![paper_output](https://user-images.githubusercontent.com/42019181/195025196-0c4aaf05-de1b-4efa-8a80-68d7fedefb79.png) If there are errors or improvements in the code, please feel free to contact me!
> > > > > 
> > > > > 
> > > > > @escapefreeg Thanks for your code. There is still some difference in my result. I run the code on a single RTX 3080, but it is useful for my next step experiment. ![image](https://user-images.githubusercontent.com/11902259/195053971-3ce14af2-6dd5-4728-acd4-35d8268f2411.png)
> > > > 
> > > > 
> > > > You‘re welcome, glad that I could help.
> > > 
> > > 
> > > Does the results in table1 tested on the training data(training view)?
> > 
> > 
> > No, The results are evaluated on test data (camera index is 1-22, and image is taken every 30 frames)
> 
> I've also download the pretrained model p387 and tested on the 22 unseen cameras, and the result is close to the paper. ![image](https://user-images.githubusercontent.com/74585868/203457749-76514c7f-9b15-4662-ba49-d71a86000e9f.png) But I download the pretained model p377 and tested on the 22 unseen views, the result is far to the paper, have you tested on p377? ![image](https://user-images.githubusercontent.com/74585868/203457938-5683bb5b-72e1-4c5d-a77d-fca42baa4509.png)

sorry, I find the bug, it's my fault.

**Comment by escapefreeg** [comment]
> > > > > > > I also wrote an evaluation code and obtained the exact same evaluation indicators in the paper. Code address: https://github.com/escapefreeg/humannerf-eval ![terminal_output](https://user-images.githubusercontent.com/42019181/195025148-35348003-e8ef-46d5-8bbd-eeeeb037935c.png) ![paper_output](https://user-images.githubusercontent.com/42019181/195025196-0c4aaf05-de1b-4efa-8a80-68d7fedefb79.png) If there are errors or improvements in the code, please feel free to contact me!
> > > > > > 
> > > > > > 
> > > > > > @escapefreeg Thanks for your code. There is still some difference in my result. I run the code on a single RTX 3080, but it is useful for my next step experiment. ![image](https://user-images.githubusercontent.com/11902259/195053971-3ce14af2-6dd5-4728-acd4-35d8268f2411.png)
> > > > > 
> > > > > 
> > > > > You‘re welcome, glad that I could help.
> > > > 
> > > > 
> > > > Does the results in table1 tested on the training data(training view)?
> > > 
> > > 
> > > No, The results are evaluated on test data (camera index is 1-22, and image is taken every 30 frames)
> > 
> > 
> > I've also download the pretrained model p387 and tested on the 22 unseen cameras, and the result is close to the paper. ![image](https://user-images.githubusercontent.com/74585868/203457749-76514c7f-9b15-4662-ba49-d71a86000e9f.png) But I download the pretained model p377 and tested on the 22 unseen views, the result is far to the paper, have you tested on p377? ![image](https://user-images.githubusercontent.com/74585868/203457938-5683bb5b-72e1-4c5d-a77d-fca42baa4509.png)
> 
> @escapefreeg sorry, I find the bug, it's my fault.

It's fine. glad you found the problem.

**Comment by Andyen512** [comment]
> 

Do you test the model in 100k, 200k ,300k iters? I tested these models but the result in RSNR, SSIM, LPIPS are not much difference. Dose the model reach convergence before 100k iter?

**Comment by shangchengPKU** [comment]
> 其实我自己写了一个评估脚本，与论文相比得到了合理的结果。请随时检查它，如果有任何问题，请告诉我。唯一的问题是你需要`skip=30`每 30 帧添加一次拾取，并`view`在 yaml 文件中进行更改。
> 
> ```
> import skimage
> import os
> 
> import torch
> import numpy as np
> from tqdm import tqdm
> from PIL import Image
> 
> from core.data import create_dataloader
> from core.nets import create_network
> from core.utils.train_util import cpu_data_to_gpu
> from core.utils.image_util import ImageWriter, to_8b_image, to_8b3ch_image
> 
> from configs import cfg, args
> 
> from third_parties.lpips import LPIPS
> 
> EXCLUDE_KEYS_TO_GPU = ['frame_name',
>                        'img_width', 'img_height']
> 
> def load_network():
>     model = create_network()
>     ckpt_path = os.path.join(cfg.logdir, f'{cfg.load_net}.tar')
>     ckpt = torch.load(ckpt_path, map_location='cuda:0')
>     model.load_state_dict(ckpt['network'], strict=False)
>     print('load network from ', ckpt_path)
>     return model.cuda().deploy_mlps_to_secondary_gpus()
> 
> 
> def unpack_alpha_map(alpha_vals, ray_mask, width, height):
>     alpha_map = np.zeros((height * width), dtype='float32')
>     alpha_map[ray_mask] = alpha_vals
>     return alpha_map.reshape((height, width))
> 
> 
> def unpack_to_image(width, height, ray_mask, bgcolor,
>                     rgb, alpha, truth=None):
>     
>     rgb_image = np.full((height * width, 3), bgcolor, dtype='float32')
>     truth_image = np.full((height * width, 3), bgcolor, dtype='float32')
> 
>     rgb_image[ray_mask] = rgb
>     rgb_image = to_8b_image(rgb_image.reshape((height, width, 3)))
> 
>     if truth is not None:
>         truth_image[ray_mask] = truth
>         truth_image = to_8b_image(truth_image.reshape((height, width, 3)))
> 
>     alpha_map = unpack_alpha_map(alpha, ray_mask, width, height)
>     alpha_image  = to_8b3ch_image(alpha_map)
> 
>     return rgb_image, alpha_image, truth_image
> 
> def psnr_metric(img_pred, img_gt):
>     mse = np.mean((img_pred - img_gt)**2)
>     psnr = -10 * np.log(mse) / np.log(10)
>     return psnr
> 
> def scale_for_lpips(image_tensor):
>     return image_tensor * 2. - 1.
> 
> 
> def get_loss(rgb, target):
>     lpips = LPIPS(net='vgg')#.cuda()
>     lpips_loss = lpips(scale_for_lpips(rgb.permute(0, 3, 1, 2)), 
>                        scale_for_lpips(target.permute(0, 3, 1, 2)))
>     return torch.mean(lpips_loss).cpu().detach().numpy()
> 
> def evaluate():
>     cfg.perturb = 0.
> 
>     psnr_l = []
>     ssim_l = []
>     lpips_l = []
> 
>     model = load_network()
>     test_loader = create_dataloader('movement')
> 
>     model.eval()
>     for idx, batch in enumerate(tqdm(test_loader)):
>         for k, v in batch.items():
>             batch[k] = v[0]
> 
>         data = cpu_data_to_gpu(
>                     batch,
>                     exclude_keys=EXCLUDE_KEYS_TO_GPU + ['target_rgbs'])
> 
>         with torch.no_grad():
>             net_output = model(**data, iter_val=cfg.eval_iter)
> 
>         rgb = net_output['rgb']
>         alpha = net_output['alpha']
> 
>         width = batch['img_width']
>         height = batch['img_height']
>         ray_mask = batch['ray_mask']
> 
>         pred_img, alpha_img, gt_img = \
>             unpack_to_image(
>                 width, height, ray_mask, np.array(cfg.bgcolor)/255.,
>                 rgb.data.cpu().numpy(),
>                 alpha.data.cpu().numpy(),
>                 batch['target_rgbs'])
> 
>         pred_img_norm = pred_img / pred_img.max()
>         gt_img_norm = gt_img / gt_img.max()
> 
>         # get evaluation
>         psnr_l.append(psnr_metric(pred_img_norm, gt_img_norm))
>         ssim_l.append(skimage.metrics.structural_similarity(pred_img_norm, gt_img_norm, multichannel=True))
>         lpips_loss = get_loss(rgb=torch.from_numpy(pred_img_norm).float().unsqueeze(0), target=torch.from_numpy(gt_img_norm).float().unsqueeze(0))
>         lpips_l.append(lpips_loss)
>         
> 
>     return psnr_l, ssim_l, lpips_l
> 
> psnr_l, ssim_l, lpips_l = evaluate()
> print (np.array(psnr_l).mean())
> print (np.array(ssim_l).mean())
> print (np.array(lpips_l).mean())
> ```

Hello, where do I need to set the view and skip=30 options?

**Comment by shangchengPKU** [comment]
> > > > > > > I also wrote an evaluation code and obtained the exact same evaluation indicators in the paper. Code address: https://github.com/escapefreeg/humannerf-eval ![terminal_output](https://user-images.githubusercontent.com/42019181/195025148-35348003-e8ef-46d5-8bbd-eeeeb037935c.png) ![paper_output](https://user-images.githubusercontent.com/42019181/195025196-0c4aaf05-de1b-4efa-8a80-68d7fedefb79.png) If there are errors or improvements in the code, please feel free to contact me!
> > > > > > 
> > > > > > 
> > > > > > @escapefreeg Thanks for your code. There is still some difference in my result. I run the code on a single RTX 3080, but it is useful for my next step experiment. ![image](https://user-images.githubusercontent.com/11902259/195053971-3ce14af2-6dd5-4728-acd4-35d8268f2411.png)
> > > > > 
> > > > > 
> > > > > You‘re welcome, glad that I could help.
> > > > 
> > > > 
> > > > Does the results in table1 tested on the training data(training view)?
> > > 
> > > 
> > > No, The results are evaluated on test data (camera index is 1-22, and image is taken every 30 frames)
> > 
> > 
> > I've also download the pretrained model p387 and tested on the 22 unseen cameras, and the result is close to the paper. ![image](https://user-images.githubusercontent.com/74585868/203457749-76514c7f-9b15-4662-ba49-d71a86000e9f.png) But I download the pretained model p377 and tested on the 22 unseen views, the result is far to the paper, have you tested on p377? ![image](https://user-images.githubusercontent.com/74585868/203457938-5683bb5b-72e1-4c5d-a77d-fca42baa4509.png)
> 
> @escapefreeg sorry, I find the bug, it's my fault.

Hello, I have encountered the same error, but I don't know where the problem is. What is the reason for this?

**Comment by Andyen512** [comment]
> > > > > > > > I also wrote an evaluation code and obtained the exact same evaluation indicators in the paper. Code address: https://github.com/escapefreeg/humannerf-eval ![terminal_output](https://user-images.githubusercontent.com/42019181/195025148-35348003-e8ef-46d5-8bbd-eeeeb037935c.png) ![paper_output](https://user-images.githubusercontent.com/42019181/195025196-0c4aaf05-de1b-4efa-8a80-68d7fedefb79.png) If there are errors or improvements in the code, please feel free to contact me!
> > > > > > > 
> > > > > > > 
> > > > > > > @escapefreeg Thanks for your code. There is still some difference in my result. I run the code on a single RTX 3080, but it is useful for my next step experiment. ![image](https://user-images.githubusercontent.com/11902259/195053971-3ce14af2-6dd5-4728-acd4-35d8268f2411.png)
> > > > > > 
> > > > > > 
> > > > > > You‘re welcome, glad that I could help.
> > > > > 
> > > > > 
> > > > > Does the results in table1 tested on the training data(training view)?
> > > > 
> > > > 
> > > > No, The results are evaluated on test data (camera index is 1-22, and image is taken every 30 frames)
> > > 
> > > 
> > > I've also download the pretrained model p387 and tested on the 22 unseen cameras, and the result is close to the paper. ![image](https://user-images.githubusercontent.com/74585868/203457749-76514c7f-9b15-4662-ba49-d71a86000e9f.png) But I download the pretained model p377 and tested on the 22 unseen views, the result is far to the paper, have you tested on p377? ![image](https://user-images.githubusercontent.com/74585868/203457938-5683bb5b-72e1-4c5d-a77d-fca42baa4509.png)
> > 
> > 
> > @escapefreeg sorry, I find the bug, it's my fault.
> 
> Hello, I have encountered the same error, but I don't know where the problem is. What is the reason for this?

Maybe  the background color you rendered is not black. When I use black as my bgcolor, the result gets better.
