### ISSUE TITLE
Can I render an arbitrary cam path with well-trained humannerf?

### ISSUE THREAD

**Issue by leviome** [chungyiweng/humannerf#80]
thanks for the great job! 

As I know, three rendering types including `freeview`, `tpose` and `movement` is ready. Is HumanNeRF able to render an arbitary camera path of movement?

**Comment by Dipankar1997161** [comment]
Can you be a little more specific on what type of cam_movement are you talking about?

**Comment by leviome** [comment]
for example, I wanna make a demo like camera moves spiral rising around a dynamic person. 

the aim of me is to render any view of any frame with inputs of cam pose and frame id.

**Comment by Dipankar1997161** [comment]
> for example, I wanna make a demo like camera moves spiral rising around a dynamic person.
> 
> the aim of me is to render any view of any frame with inputs of cam pose and frame id.

You can create any movement of the camera. Just play with the following function 
https://github.com/chungyiweng/humannerf/blob/d1a623c0e43dc15f112ed0b62d4a8fa487c7e5d2/core/data/human_nerf/freeview.py#L129

This controls the render camera movement

**Comment by leviome** [comment]
Thanks 🙏
