### ISSUE TITLE
generate mesh

### ISSUE THREAD

**Issue by ssy-sheshe** [chungyiweng/humannerf#9]
Is there the code that generate mesh, for example,  the code neural body provided.Can you realse it？
thanks！

**Comment by chungyiweng** [comment]
Thanks for the feedback. But currently, I don't have a plan to provide the code for generating meshes as it's not our research focus. Sorry about this.

**Comment by HWP97** [comment]
> Is there the code that generate mesh, for example, the code neural body provided.Can you realse it？ thanks！

Did you implement the code that generates mesh for humannerf?
If you implemented it, could you provide the code?
thanks.
